version: '3.9'

services:

  migrate:
    image: "migrate/migrate"
    networks:
      - TurkNet
    volumes:
      - ./migrations:/migrations
    command:
      [ "-path", "/migrations",
        "-database", "postgres://postgres:dodi@postgres_national:5432/cm?sslmode=disable",
        "up"
      ]
    depends_on:
      postgres_national:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h postgres_national -U postgres -d cm"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres_national:
    image: postgres:16.3
    container_name: postgres_national
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dodi
      - POSTGRES_DB=cm
    networks:
      - TurkNet
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # Ensure the health check targets the right host/port inside the container
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432 -U postgres -d cm" ]
      interval: 30s
      timeout: 10s
      retries: 5

  turk-national:
    build: .
    ports:
      - 7080:7080
    networks:
      - TurkNet
    depends_on:
      postgres_national:
        condition: service_healthy
    healthcheck:
      # Make sure your app exposes a `/health` endpoint or use a basic HTTP check
      test: ["CMD", "curl", "-f", "http://localhost:7080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  TurkNet:
    name: TurkNet
    driver: bridge

volumes:
  postgres_data:
