// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: nationality/nationality.proto

package nationality

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NationalityServiceClient is the client API for NationalityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NationalityServiceClient interface {
	// National Foods
	CreateNationalFood(ctx context.Context, in *NationalFood, opts ...grpc.CallOption) (*NationalFoodResponse, error)
	UpdateNationalFoods(ctx context.Context, in *UpdateNationalFood, opts ...grpc.CallOption) (*NationalFoodResponse, error)
	GetNationalFoodByID(ctx context.Context, in *NationalFoodId, opts ...grpc.CallOption) (*NationalFoodResponse, error)
	ListNationalFood(ctx context.Context, in *NationalFoodList, opts ...grpc.CallOption) (*NationalFoodListResponse, error)
	DeleteNationalFood(ctx context.Context, in *NationalFoodId, opts ...grpc.CallOption) (*Message, error)
	AddNationalFoodImage(ctx context.Context, in *NationalFoodImage, opts ...grpc.CallOption) (*Message, error)
	RemoveNationalFoodImage(ctx context.Context, in *NationalFoodImage, opts ...grpc.CallOption) (*Message, error)
	GetNationalFoodByCountry(ctx context.Context, in *NationalFoodCountry, opts ...grpc.CallOption) (*NationalFoodListResponse, error)
	SearchNationalFood(ctx context.Context, in *NationalFoodSearch, opts ...grpc.CallOption) (*NationalFoodListResponse, error)
	GetRatingNationalFood(ctx context.Context, in *NationalFoodId, opts ...grpc.CallOption) (*RatingResponse, error)
	// Historical
	AddHistorical(ctx context.Context, in *Historical, opts ...grpc.CallOption) (*HistoricalResponse, error)
	UpdateHistoricals(ctx context.Context, in *UpdateHistorical, opts ...grpc.CallOption) (*HistoricalResponse, error)
	GetHistoricalByID(ctx context.Context, in *HistoricalId, opts ...grpc.CallOption) (*HistoricalResponse, error)
	ListHistorical(ctx context.Context, in *HistoricalList, opts ...grpc.CallOption) (*HistoricalListResponse, error)
	DeleteHistorical(ctx context.Context, in *HistoricalId, opts ...grpc.CallOption) (*Message, error)
	SearchHistorical(ctx context.Context, in *HistoricalSearch, opts ...grpc.CallOption) (*HistoricalListResponse, error)
	GetHistoricalByCountry(ctx context.Context, in *HistoricalCountry, opts ...grpc.CallOption) (*HistoricalListResponse, error)
	AddHistoricalImage(ctx context.Context, in *HistoricalImage, opts ...grpc.CallOption) (*Message, error)
	RemoveHistoricalImage(ctx context.Context, in *HistoricalImage, opts ...grpc.CallOption) (*Message, error)
	// Attractions
	CreateAttraction(ctx context.Context, in *Attraction, opts ...grpc.CallOption) (*AttractionResponse, error)
	UpdateAttractions(ctx context.Context, in *UpdateAttraction, opts ...grpc.CallOption) (*AttractionResponse, error)
	GetAttractionByID(ctx context.Context, in *AttractionId, opts ...grpc.CallOption) (*AttractionResponse, error)
	ListAttraction(ctx context.Context, in *AttractionList, opts ...grpc.CallOption) (*AttractionListResponse, error)
	DeleteAttraction(ctx context.Context, in *AttractionId, opts ...grpc.CallOption) (*Message, error)
	AddAttractionImage(ctx context.Context, in *AttractionImage, opts ...grpc.CallOption) (*Message, error)
	RemoveAttractionImage(ctx context.Context, in *AttractionImage, opts ...grpc.CallOption) (*Message, error)
	SearchAttraction(ctx context.Context, in *AttractionSearch, opts ...grpc.CallOption) (*AttractionListResponse, error)
	CreateAttractionType(ctx context.Context, in *CreateAttractionTypeRequest, opts ...grpc.CallOption) (*CreateAttractionTypeResponse, error)
	GetAttractionType(ctx context.Context, in *GetAttractionTypeRequest, opts ...grpc.CallOption) (*GetAttractionTypeResponse, error)
	UpdateAttractionType(ctx context.Context, in *UpdateAttractionTypeRequest, opts ...grpc.CallOption) (*UpdateAttractionTypeResponse, error)
	DeleteAttractionType(ctx context.Context, in *DeleteAttractionTypeRequest, opts ...grpc.CallOption) (*Message, error)
	ListAttractionTypes(ctx context.Context, in *ListAttractionTypesRequest, opts ...grpc.CallOption) (*ListAttractionTypesResponse, error)
}

type nationalityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNationalityServiceClient(cc grpc.ClientConnInterface) NationalityServiceClient {
	return &nationalityServiceClient{cc}
}

func (c *nationalityServiceClient) CreateNationalFood(ctx context.Context, in *NationalFood, opts ...grpc.CallOption) (*NationalFoodResponse, error) {
	out := new(NationalFoodResponse)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/CreateNationalFood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) UpdateNationalFoods(ctx context.Context, in *UpdateNationalFood, opts ...grpc.CallOption) (*NationalFoodResponse, error) {
	out := new(NationalFoodResponse)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/UpdateNationalFoods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) GetNationalFoodByID(ctx context.Context, in *NationalFoodId, opts ...grpc.CallOption) (*NationalFoodResponse, error) {
	out := new(NationalFoodResponse)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/GetNationalFoodByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) ListNationalFood(ctx context.Context, in *NationalFoodList, opts ...grpc.CallOption) (*NationalFoodListResponse, error) {
	out := new(NationalFoodListResponse)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/ListNationalFood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) DeleteNationalFood(ctx context.Context, in *NationalFoodId, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/DeleteNationalFood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) AddNationalFoodImage(ctx context.Context, in *NationalFoodImage, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/AddNationalFoodImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) RemoveNationalFoodImage(ctx context.Context, in *NationalFoodImage, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/RemoveNationalFoodImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) GetNationalFoodByCountry(ctx context.Context, in *NationalFoodCountry, opts ...grpc.CallOption) (*NationalFoodListResponse, error) {
	out := new(NationalFoodListResponse)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/GetNationalFoodByCountry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) SearchNationalFood(ctx context.Context, in *NationalFoodSearch, opts ...grpc.CallOption) (*NationalFoodListResponse, error) {
	out := new(NationalFoodListResponse)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/SearchNationalFood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) GetRatingNationalFood(ctx context.Context, in *NationalFoodId, opts ...grpc.CallOption) (*RatingResponse, error) {
	out := new(RatingResponse)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/GetRatingNationalFood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) AddHistorical(ctx context.Context, in *Historical, opts ...grpc.CallOption) (*HistoricalResponse, error) {
	out := new(HistoricalResponse)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/AddHistorical", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) UpdateHistoricals(ctx context.Context, in *UpdateHistorical, opts ...grpc.CallOption) (*HistoricalResponse, error) {
	out := new(HistoricalResponse)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/UpdateHistoricals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) GetHistoricalByID(ctx context.Context, in *HistoricalId, opts ...grpc.CallOption) (*HistoricalResponse, error) {
	out := new(HistoricalResponse)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/GetHistoricalByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) ListHistorical(ctx context.Context, in *HistoricalList, opts ...grpc.CallOption) (*HistoricalListResponse, error) {
	out := new(HistoricalListResponse)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/ListHistorical", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) DeleteHistorical(ctx context.Context, in *HistoricalId, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/DeleteHistorical", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) SearchHistorical(ctx context.Context, in *HistoricalSearch, opts ...grpc.CallOption) (*HistoricalListResponse, error) {
	out := new(HistoricalListResponse)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/SearchHistorical", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) GetHistoricalByCountry(ctx context.Context, in *HistoricalCountry, opts ...grpc.CallOption) (*HistoricalListResponse, error) {
	out := new(HistoricalListResponse)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/GetHistoricalByCountry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) AddHistoricalImage(ctx context.Context, in *HistoricalImage, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/AddHistoricalImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) RemoveHistoricalImage(ctx context.Context, in *HistoricalImage, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/RemoveHistoricalImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) CreateAttraction(ctx context.Context, in *Attraction, opts ...grpc.CallOption) (*AttractionResponse, error) {
	out := new(AttractionResponse)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/CreateAttraction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) UpdateAttractions(ctx context.Context, in *UpdateAttraction, opts ...grpc.CallOption) (*AttractionResponse, error) {
	out := new(AttractionResponse)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/UpdateAttractions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) GetAttractionByID(ctx context.Context, in *AttractionId, opts ...grpc.CallOption) (*AttractionResponse, error) {
	out := new(AttractionResponse)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/GetAttractionByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) ListAttraction(ctx context.Context, in *AttractionList, opts ...grpc.CallOption) (*AttractionListResponse, error) {
	out := new(AttractionListResponse)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/ListAttraction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) DeleteAttraction(ctx context.Context, in *AttractionId, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/DeleteAttraction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) AddAttractionImage(ctx context.Context, in *AttractionImage, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/AddAttractionImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) RemoveAttractionImage(ctx context.Context, in *AttractionImage, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/RemoveAttractionImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) SearchAttraction(ctx context.Context, in *AttractionSearch, opts ...grpc.CallOption) (*AttractionListResponse, error) {
	out := new(AttractionListResponse)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/SearchAttraction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) CreateAttractionType(ctx context.Context, in *CreateAttractionTypeRequest, opts ...grpc.CallOption) (*CreateAttractionTypeResponse, error) {
	out := new(CreateAttractionTypeResponse)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/CreateAttractionType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) GetAttractionType(ctx context.Context, in *GetAttractionTypeRequest, opts ...grpc.CallOption) (*GetAttractionTypeResponse, error) {
	out := new(GetAttractionTypeResponse)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/GetAttractionType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) UpdateAttractionType(ctx context.Context, in *UpdateAttractionTypeRequest, opts ...grpc.CallOption) (*UpdateAttractionTypeResponse, error) {
	out := new(UpdateAttractionTypeResponse)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/UpdateAttractionType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) DeleteAttractionType(ctx context.Context, in *DeleteAttractionTypeRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/DeleteAttractionType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nationalityServiceClient) ListAttractionTypes(ctx context.Context, in *ListAttractionTypesRequest, opts ...grpc.CallOption) (*ListAttractionTypesResponse, error) {
	out := new(ListAttractionTypesResponse)
	err := c.cc.Invoke(ctx, "/nationality.NationalityService/ListAttractionTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NationalityServiceServer is the server API for NationalityService service.
// All implementations must embed UnimplementedNationalityServiceServer
// for forward compatibility
type NationalityServiceServer interface {
	// National Foods
	CreateNationalFood(context.Context, *NationalFood) (*NationalFoodResponse, error)
	UpdateNationalFoods(context.Context, *UpdateNationalFood) (*NationalFoodResponse, error)
	GetNationalFoodByID(context.Context, *NationalFoodId) (*NationalFoodResponse, error)
	ListNationalFood(context.Context, *NationalFoodList) (*NationalFoodListResponse, error)
	DeleteNationalFood(context.Context, *NationalFoodId) (*Message, error)
	AddNationalFoodImage(context.Context, *NationalFoodImage) (*Message, error)
	RemoveNationalFoodImage(context.Context, *NationalFoodImage) (*Message, error)
	GetNationalFoodByCountry(context.Context, *NationalFoodCountry) (*NationalFoodListResponse, error)
	SearchNationalFood(context.Context, *NationalFoodSearch) (*NationalFoodListResponse, error)
	GetRatingNationalFood(context.Context, *NationalFoodId) (*RatingResponse, error)
	// Historical
	AddHistorical(context.Context, *Historical) (*HistoricalResponse, error)
	UpdateHistoricals(context.Context, *UpdateHistorical) (*HistoricalResponse, error)
	GetHistoricalByID(context.Context, *HistoricalId) (*HistoricalResponse, error)
	ListHistorical(context.Context, *HistoricalList) (*HistoricalListResponse, error)
	DeleteHistorical(context.Context, *HistoricalId) (*Message, error)
	SearchHistorical(context.Context, *HistoricalSearch) (*HistoricalListResponse, error)
	GetHistoricalByCountry(context.Context, *HistoricalCountry) (*HistoricalListResponse, error)
	AddHistoricalImage(context.Context, *HistoricalImage) (*Message, error)
	RemoveHistoricalImage(context.Context, *HistoricalImage) (*Message, error)
	// Attractions
	CreateAttraction(context.Context, *Attraction) (*AttractionResponse, error)
	UpdateAttractions(context.Context, *UpdateAttraction) (*AttractionResponse, error)
	GetAttractionByID(context.Context, *AttractionId) (*AttractionResponse, error)
	ListAttraction(context.Context, *AttractionList) (*AttractionListResponse, error)
	DeleteAttraction(context.Context, *AttractionId) (*Message, error)
	AddAttractionImage(context.Context, *AttractionImage) (*Message, error)
	RemoveAttractionImage(context.Context, *AttractionImage) (*Message, error)
	SearchAttraction(context.Context, *AttractionSearch) (*AttractionListResponse, error)
	CreateAttractionType(context.Context, *CreateAttractionTypeRequest) (*CreateAttractionTypeResponse, error)
	GetAttractionType(context.Context, *GetAttractionTypeRequest) (*GetAttractionTypeResponse, error)
	UpdateAttractionType(context.Context, *UpdateAttractionTypeRequest) (*UpdateAttractionTypeResponse, error)
	DeleteAttractionType(context.Context, *DeleteAttractionTypeRequest) (*Message, error)
	ListAttractionTypes(context.Context, *ListAttractionTypesRequest) (*ListAttractionTypesResponse, error)
	mustEmbedUnimplementedNationalityServiceServer()
}

// UnimplementedNationalityServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNationalityServiceServer struct {
}

func (UnimplementedNationalityServiceServer) CreateNationalFood(context.Context, *NationalFood) (*NationalFoodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNationalFood not implemented")
}
func (UnimplementedNationalityServiceServer) UpdateNationalFoods(context.Context, *UpdateNationalFood) (*NationalFoodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNationalFoods not implemented")
}
func (UnimplementedNationalityServiceServer) GetNationalFoodByID(context.Context, *NationalFoodId) (*NationalFoodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNationalFoodByID not implemented")
}
func (UnimplementedNationalityServiceServer) ListNationalFood(context.Context, *NationalFoodList) (*NationalFoodListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNationalFood not implemented")
}
func (UnimplementedNationalityServiceServer) DeleteNationalFood(context.Context, *NationalFoodId) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNationalFood not implemented")
}
func (UnimplementedNationalityServiceServer) AddNationalFoodImage(context.Context, *NationalFoodImage) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNationalFoodImage not implemented")
}
func (UnimplementedNationalityServiceServer) RemoveNationalFoodImage(context.Context, *NationalFoodImage) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveNationalFoodImage not implemented")
}
func (UnimplementedNationalityServiceServer) GetNationalFoodByCountry(context.Context, *NationalFoodCountry) (*NationalFoodListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNationalFoodByCountry not implemented")
}
func (UnimplementedNationalityServiceServer) SearchNationalFood(context.Context, *NationalFoodSearch) (*NationalFoodListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchNationalFood not implemented")
}
func (UnimplementedNationalityServiceServer) GetRatingNationalFood(context.Context, *NationalFoodId) (*RatingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRatingNationalFood not implemented")
}
func (UnimplementedNationalityServiceServer) AddHistorical(context.Context, *Historical) (*HistoricalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddHistorical not implemented")
}
func (UnimplementedNationalityServiceServer) UpdateHistoricals(context.Context, *UpdateHistorical) (*HistoricalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHistoricals not implemented")
}
func (UnimplementedNationalityServiceServer) GetHistoricalByID(context.Context, *HistoricalId) (*HistoricalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistoricalByID not implemented")
}
func (UnimplementedNationalityServiceServer) ListHistorical(context.Context, *HistoricalList) (*HistoricalListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHistorical not implemented")
}
func (UnimplementedNationalityServiceServer) DeleteHistorical(context.Context, *HistoricalId) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHistorical not implemented")
}
func (UnimplementedNationalityServiceServer) SearchHistorical(context.Context, *HistoricalSearch) (*HistoricalListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchHistorical not implemented")
}
func (UnimplementedNationalityServiceServer) GetHistoricalByCountry(context.Context, *HistoricalCountry) (*HistoricalListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistoricalByCountry not implemented")
}
func (UnimplementedNationalityServiceServer) AddHistoricalImage(context.Context, *HistoricalImage) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddHistoricalImage not implemented")
}
func (UnimplementedNationalityServiceServer) RemoveHistoricalImage(context.Context, *HistoricalImage) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveHistoricalImage not implemented")
}
func (UnimplementedNationalityServiceServer) CreateAttraction(context.Context, *Attraction) (*AttractionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAttraction not implemented")
}
func (UnimplementedNationalityServiceServer) UpdateAttractions(context.Context, *UpdateAttraction) (*AttractionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAttractions not implemented")
}
func (UnimplementedNationalityServiceServer) GetAttractionByID(context.Context, *AttractionId) (*AttractionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttractionByID not implemented")
}
func (UnimplementedNationalityServiceServer) ListAttraction(context.Context, *AttractionList) (*AttractionListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAttraction not implemented")
}
func (UnimplementedNationalityServiceServer) DeleteAttraction(context.Context, *AttractionId) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAttraction not implemented")
}
func (UnimplementedNationalityServiceServer) AddAttractionImage(context.Context, *AttractionImage) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAttractionImage not implemented")
}
func (UnimplementedNationalityServiceServer) RemoveAttractionImage(context.Context, *AttractionImage) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveAttractionImage not implemented")
}
func (UnimplementedNationalityServiceServer) SearchAttraction(context.Context, *AttractionSearch) (*AttractionListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchAttraction not implemented")
}
func (UnimplementedNationalityServiceServer) CreateAttractionType(context.Context, *CreateAttractionTypeRequest) (*CreateAttractionTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAttractionType not implemented")
}
func (UnimplementedNationalityServiceServer) GetAttractionType(context.Context, *GetAttractionTypeRequest) (*GetAttractionTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttractionType not implemented")
}
func (UnimplementedNationalityServiceServer) UpdateAttractionType(context.Context, *UpdateAttractionTypeRequest) (*UpdateAttractionTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAttractionType not implemented")
}
func (UnimplementedNationalityServiceServer) DeleteAttractionType(context.Context, *DeleteAttractionTypeRequest) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAttractionType not implemented")
}
func (UnimplementedNationalityServiceServer) ListAttractionTypes(context.Context, *ListAttractionTypesRequest) (*ListAttractionTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAttractionTypes not implemented")
}
func (UnimplementedNationalityServiceServer) mustEmbedUnimplementedNationalityServiceServer() {}

// UnsafeNationalityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NationalityServiceServer will
// result in compilation errors.
type UnsafeNationalityServiceServer interface {
	mustEmbedUnimplementedNationalityServiceServer()
}

func RegisterNationalityServiceServer(s grpc.ServiceRegistrar, srv NationalityServiceServer) {
	s.RegisterService(&NationalityService_ServiceDesc, srv)
}

func _NationalityService_CreateNationalFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NationalFood)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).CreateNationalFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/CreateNationalFood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).CreateNationalFood(ctx, req.(*NationalFood))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_UpdateNationalFoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNationalFood)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).UpdateNationalFoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/UpdateNationalFoods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).UpdateNationalFoods(ctx, req.(*UpdateNationalFood))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_GetNationalFoodByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NationalFoodId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).GetNationalFoodByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/GetNationalFoodByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).GetNationalFoodByID(ctx, req.(*NationalFoodId))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_ListNationalFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NationalFoodList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).ListNationalFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/ListNationalFood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).ListNationalFood(ctx, req.(*NationalFoodList))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_DeleteNationalFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NationalFoodId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).DeleteNationalFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/DeleteNationalFood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).DeleteNationalFood(ctx, req.(*NationalFoodId))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_AddNationalFoodImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NationalFoodImage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).AddNationalFoodImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/AddNationalFoodImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).AddNationalFoodImage(ctx, req.(*NationalFoodImage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_RemoveNationalFoodImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NationalFoodImage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).RemoveNationalFoodImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/RemoveNationalFoodImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).RemoveNationalFoodImage(ctx, req.(*NationalFoodImage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_GetNationalFoodByCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NationalFoodCountry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).GetNationalFoodByCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/GetNationalFoodByCountry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).GetNationalFoodByCountry(ctx, req.(*NationalFoodCountry))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_SearchNationalFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NationalFoodSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).SearchNationalFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/SearchNationalFood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).SearchNationalFood(ctx, req.(*NationalFoodSearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_GetRatingNationalFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NationalFoodId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).GetRatingNationalFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/GetRatingNationalFood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).GetRatingNationalFood(ctx, req.(*NationalFoodId))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_AddHistorical_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Historical)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).AddHistorical(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/AddHistorical",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).AddHistorical(ctx, req.(*Historical))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_UpdateHistoricals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHistorical)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).UpdateHistoricals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/UpdateHistoricals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).UpdateHistoricals(ctx, req.(*UpdateHistorical))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_GetHistoricalByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoricalId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).GetHistoricalByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/GetHistoricalByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).GetHistoricalByID(ctx, req.(*HistoricalId))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_ListHistorical_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoricalList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).ListHistorical(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/ListHistorical",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).ListHistorical(ctx, req.(*HistoricalList))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_DeleteHistorical_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoricalId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).DeleteHistorical(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/DeleteHistorical",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).DeleteHistorical(ctx, req.(*HistoricalId))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_SearchHistorical_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoricalSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).SearchHistorical(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/SearchHistorical",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).SearchHistorical(ctx, req.(*HistoricalSearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_GetHistoricalByCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoricalCountry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).GetHistoricalByCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/GetHistoricalByCountry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).GetHistoricalByCountry(ctx, req.(*HistoricalCountry))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_AddHistoricalImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoricalImage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).AddHistoricalImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/AddHistoricalImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).AddHistoricalImage(ctx, req.(*HistoricalImage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_RemoveHistoricalImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoricalImage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).RemoveHistoricalImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/RemoveHistoricalImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).RemoveHistoricalImage(ctx, req.(*HistoricalImage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_CreateAttraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Attraction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).CreateAttraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/CreateAttraction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).CreateAttraction(ctx, req.(*Attraction))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_UpdateAttractions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAttraction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).UpdateAttractions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/UpdateAttractions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).UpdateAttractions(ctx, req.(*UpdateAttraction))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_GetAttractionByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttractionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).GetAttractionByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/GetAttractionByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).GetAttractionByID(ctx, req.(*AttractionId))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_ListAttraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttractionList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).ListAttraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/ListAttraction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).ListAttraction(ctx, req.(*AttractionList))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_DeleteAttraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttractionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).DeleteAttraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/DeleteAttraction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).DeleteAttraction(ctx, req.(*AttractionId))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_AddAttractionImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttractionImage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).AddAttractionImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/AddAttractionImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).AddAttractionImage(ctx, req.(*AttractionImage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_RemoveAttractionImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttractionImage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).RemoveAttractionImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/RemoveAttractionImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).RemoveAttractionImage(ctx, req.(*AttractionImage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_SearchAttraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttractionSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).SearchAttraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/SearchAttraction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).SearchAttraction(ctx, req.(*AttractionSearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_CreateAttractionType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAttractionTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).CreateAttractionType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/CreateAttractionType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).CreateAttractionType(ctx, req.(*CreateAttractionTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_GetAttractionType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttractionTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).GetAttractionType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/GetAttractionType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).GetAttractionType(ctx, req.(*GetAttractionTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_UpdateAttractionType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAttractionTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).UpdateAttractionType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/UpdateAttractionType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).UpdateAttractionType(ctx, req.(*UpdateAttractionTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_DeleteAttractionType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAttractionTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).DeleteAttractionType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/DeleteAttractionType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).DeleteAttractionType(ctx, req.(*DeleteAttractionTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NationalityService_ListAttractionTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAttractionTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NationalityServiceServer).ListAttractionTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nationality.NationalityService/ListAttractionTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NationalityServiceServer).ListAttractionTypes(ctx, req.(*ListAttractionTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NationalityService_ServiceDesc is the grpc.ServiceDesc for NationalityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NationalityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nationality.NationalityService",
	HandlerType: (*NationalityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNationalFood",
			Handler:    _NationalityService_CreateNationalFood_Handler,
		},
		{
			MethodName: "UpdateNationalFoods",
			Handler:    _NationalityService_UpdateNationalFoods_Handler,
		},
		{
			MethodName: "GetNationalFoodByID",
			Handler:    _NationalityService_GetNationalFoodByID_Handler,
		},
		{
			MethodName: "ListNationalFood",
			Handler:    _NationalityService_ListNationalFood_Handler,
		},
		{
			MethodName: "DeleteNationalFood",
			Handler:    _NationalityService_DeleteNationalFood_Handler,
		},
		{
			MethodName: "AddNationalFoodImage",
			Handler:    _NationalityService_AddNationalFoodImage_Handler,
		},
		{
			MethodName: "RemoveNationalFoodImage",
			Handler:    _NationalityService_RemoveNationalFoodImage_Handler,
		},
		{
			MethodName: "GetNationalFoodByCountry",
			Handler:    _NationalityService_GetNationalFoodByCountry_Handler,
		},
		{
			MethodName: "SearchNationalFood",
			Handler:    _NationalityService_SearchNationalFood_Handler,
		},
		{
			MethodName: "GetRatingNationalFood",
			Handler:    _NationalityService_GetRatingNationalFood_Handler,
		},
		{
			MethodName: "AddHistorical",
			Handler:    _NationalityService_AddHistorical_Handler,
		},
		{
			MethodName: "UpdateHistoricals",
			Handler:    _NationalityService_UpdateHistoricals_Handler,
		},
		{
			MethodName: "GetHistoricalByID",
			Handler:    _NationalityService_GetHistoricalByID_Handler,
		},
		{
			MethodName: "ListHistorical",
			Handler:    _NationalityService_ListHistorical_Handler,
		},
		{
			MethodName: "DeleteHistorical",
			Handler:    _NationalityService_DeleteHistorical_Handler,
		},
		{
			MethodName: "SearchHistorical",
			Handler:    _NationalityService_SearchHistorical_Handler,
		},
		{
			MethodName: "GetHistoricalByCountry",
			Handler:    _NationalityService_GetHistoricalByCountry_Handler,
		},
		{
			MethodName: "AddHistoricalImage",
			Handler:    _NationalityService_AddHistoricalImage_Handler,
		},
		{
			MethodName: "RemoveHistoricalImage",
			Handler:    _NationalityService_RemoveHistoricalImage_Handler,
		},
		{
			MethodName: "CreateAttraction",
			Handler:    _NationalityService_CreateAttraction_Handler,
		},
		{
			MethodName: "UpdateAttractions",
			Handler:    _NationalityService_UpdateAttractions_Handler,
		},
		{
			MethodName: "GetAttractionByID",
			Handler:    _NationalityService_GetAttractionByID_Handler,
		},
		{
			MethodName: "ListAttraction",
			Handler:    _NationalityService_ListAttraction_Handler,
		},
		{
			MethodName: "DeleteAttraction",
			Handler:    _NationalityService_DeleteAttraction_Handler,
		},
		{
			MethodName: "AddAttractionImage",
			Handler:    _NationalityService_AddAttractionImage_Handler,
		},
		{
			MethodName: "RemoveAttractionImage",
			Handler:    _NationalityService_RemoveAttractionImage_Handler,
		},
		{
			MethodName: "SearchAttraction",
			Handler:    _NationalityService_SearchAttraction_Handler,
		},
		{
			MethodName: "CreateAttractionType",
			Handler:    _NationalityService_CreateAttractionType_Handler,
		},
		{
			MethodName: "GetAttractionType",
			Handler:    _NationalityService_GetAttractionType_Handler,
		},
		{
			MethodName: "UpdateAttractionType",
			Handler:    _NationalityService_UpdateAttractionType_Handler,
		},
		{
			MethodName: "DeleteAttractionType",
			Handler:    _NationalityService_DeleteAttractionType_Handler,
		},
		{
			MethodName: "ListAttractionTypes",
			Handler:    _NationalityService_ListAttractionTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nationality/nationality.proto",
}
